# visualizations/candlestick.py
"""Plotly candlestick chart with technical indicator overlays.
The function ``plot_candlestick`` expects a DataFrame that already contains the
indicator columns generated by ``analytics.indicators.compute_all_indicators``.
It returns a ``plotly.graph_objects.Figure`` ready to be displayed via
``st.plotly_chart``.
"""

import plotly.graph_objects as go
import pandas as pd


def plot_candlestick(df: pd.DataFrame, ticker: str) -> go.Figure:
    """Create a candlestick chart with SMA, EMA and Bollinger Bands.

    Parameters
    ----------
    df: pd.DataFrame
        DataFrame with OHLCV columns and indicator columns.
    ticker: str
        The ticker symbol to display in the title.

    Returns
    -------
    go.Figure
        Plotly figure containing the chart.
    """
    fig = go.Figure()

    # Candlestick trace
    fig.add_trace(
        go.Candlestick(
            x=df.index,
            open=df["Open"],
            high=df["High"],
            low=df["Low"],
            close=df["Close"],
            name="Price",
        )
    )

    # Simple Moving Averages
    if "SMA20" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["SMA20"], mode="lines", name="SMA20", line=dict(color="#00D4FF")))
    if "SMA50" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["SMA50"], mode="lines", name="SMA50", line=dict(color="#9B59B6")))

    # EMA20
    if "EMA20" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["EMA20"], mode="lines", name="EMA20", line=dict(color="#FF4560")))

    # Bollinger Bands
    if "BB_Upper" in df.columns and "BB_Lower" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["BB_Upper"], line=dict(color="#00E396", width=1), name="BB Upper", opacity=0.5))
        fig.add_trace(go.Scatter(x=df.index, y=df["BB_Lower"], line=dict(color="#FF4560", width=1), name="BB Lower", opacity=0.5))
        # Shade the area between bands
        fig.add_trace(
            go.Scatter(
                x=list(df.index) + list(df.index[::-1]),
                y=list(df["BB_Upper"]) + list(df["BB_Lower"][::-1]),
                fill="toself",
                fillcolor="rgba(173,216,230,0.2)",
                line=dict(color="rgba(255,255,255,0)"),
                hoverinfo="skip",
                showlegend=False,
            )
        )

    # VWAP line
    if "VWAP" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["VWAP"], mode="lines", name="VWAP", line=dict(color="#FEB019", dash="dot")))

    fig.update_layout(
        title=f"{ticker} – Candlestick with Indicators",
        xaxis_title="Date",
        yaxis_title="Price (₹)",
        xaxis_rangeslider_visible=False,
        template="plotly_dark",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    return fig
